version: "3.9"
services:
    dev:
        container_name: stochastic_xai_dev
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - ~/.cache/pip:/root/.cache/pip
        working_dir: /app
        tty: true
        stdin_open: true
